[elm]
name = "virtio.block"
version = "0.1.0"
kind = "driver"
source = "kernel-tree:drivers.virtio-block"
mode = "m"

[[dependencies]]
provider = "virtio.framework"
contract = "driver.virtio.framework@1"
crate = "virtio"

[[profiles]]
id = "contest-2026"
priority = "100"
