[package]
name = "hal"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doctest = false
bench = false

[dependencies]
arch = { path = "../arch" }
elm_model = { package = "elm", path = "../libs/elm", default-features = false, features = ["runtime-model"] }
elf = { path = "../libs/elf" }
general = { path = "../general" }
kernel-symbols = { path = "../libs/kernel-symbols" }
native-abi = { path = "../libs/native-abi" }
sched = { path = "../libs/sched" }
