[workspace]
resolver = "2"
members = [
    "libs/ktest",
    "libs/ktest/ktest-mock",
    "libs/errno",
    "libs/log",
    "libs/efi",
    "libs/elf",
    "libs/mm",
    "libs/sched",
    "libs/allocator",
    "libs/socket",
    "libs/net",
    "libs/vfs",
    "libs/acpi",
    "libs/fatfs",
    "libs/extfs",
    "libs/elm",
    "libs/elm/macros",
    "libs/elm-loader",
    "libs/kernel-symbols",
    "libs/kernel-symbols/macros",
    "libs/mygo-smoltcp",
    "arch",
    "hal",
    "general",
    "kernel"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
