[workspace]
resolver = "2"
members = [
    "libs/ktest",
    "libs/ktest/ktest-mock",
    "libs/errno",
    "libs/log",
    "libs/profiling",
    "libs/efi",
    "libs/elf",
    "libs/mm",
    "libs/sched",
    "libs/allocator",
    "libs/socket",
    "libs/net",
    "libs/vfs",
    "libs/acpi",
    "libs/fatfs",
    "libs/extfs",
    "libs/elm",
    "libs/elm/macros",
    "libs/elm-loader",
    "libs/kernel-symbols",
    "libs/kernel-symbols/macros",
    "libs/kcsan",
    "arch",
    "hal",
    "general",
    "kernel"
]
exclude = [
    "drivers/cfi-flash",
    "drivers/firmware-bus",
    "drivers/fw-cfg",
    "drivers/goldfish-rtc",
    "drivers/loongson-irq",
    "drivers/loopback",
    "drivers/net-stack",
    "drivers/ls7a-rtc",
    "drivers/plic",
    "drivers/random",
    "drivers/syscon",
    "drivers/uart16550",
    "drivers/virtio",
    "drivers/virtio-blk",
    "drivers/virtio-net",
    "tests/elm/kernel-mixin",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
