[workspace]
resolver = "2"
default-members = ["kernel"]
members = [
    "libs/fdt",
    "libs/ktest",
    "libs/ktest/ktest-mock",
    "libs/errno",
    "libs/log",
    "libs/profiling",
    "libs/efi",
    "libs/elf",
    "libs/native-abi",
    "libs/soyo",
    "libs/mm",
    "libs/sched",
    "libs/allocator",
    "libs/socket",
    "libs/net",
    "libs/vfs",
    "libs/fatfs",
    "libs/extfs",
    "libs/elm",
    "libs/elm/macros",
    "libs/elm-loader",
    "libs/elm-language-abi",
    "libs/kernel-symbols",
    "libs/kernel-symbols/macros",
    "libs/kcsan",
    "arch",
    "hal",
    "general",
    "kernel",
    "xtask",
    "drivers/*",
    "drivers/virtio/api",
    "drivers/virtio/provider-api",
    "drivers/virtio/consumer-api"
]
exclude = ["tests/elm/kernel-mixin"]

[workspace.dependencies]
acpi = { version = "=5.2.0", default-features = false }
aml = "=0.16.4"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
license-file = "LICENSE"
repository = "https://github.com/redstone6835/hitoshizuku"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(elm_integrated_phase, values("device", "runtime"))'] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = false
strip = false
