[package]
name = "general"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doctest = false
bench = false

[dependencies]
acpi = { path = "../libs/acpi", default-features = false }
allocator = { path = "../libs/allocator" }
efi = { path = "../libs/efi" }
errno = { path = "../libs/errno" }
extfs = { path = "../libs/extfs" }
fatfs = { path = "../libs/fatfs" }
log = { path = "../libs/log" }
mm = { path = "../libs/mm" }
sched = { path = "../libs/sched" }
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }
vfs = { path = "../libs/vfs" }
