[package]
name = "vfs"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[features]
performance-profile = [
    "dep:profiling",
    "sched/performance-profile",
    "socket/performance-profile",
]

[dependencies]
elm_model = { package = "elm", path = "../elm" }
errno = { path = "../errno" }
kernel-symbols = { path = "../kernel-symbols" }
mm = { path = "../mm" }
net = { path = "../net" }
profiling = { path = "../profiling", optional = true }
ns = { path = "../ns", default-features = false }
sched = { path = "../sched" }
socket = { path = "../socket" }
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }

[dev-dependencies]
ktest = { path = "../ktest" }
