[package]
name = "net"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[dependencies]
hashbrown = { version = "0.17.1", default-features = false }
sched = { path = "../sched" }
spin = { version = "0.9", default-features = false, features = ["spin_mutex", "rwlock"] }
