[package]
name = "net"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[features]
performance-profile = ["dep:profiling"]

[dependencies]
elm_model = { package = "elm", path = "../elm" }
hashbrown = { version = "0.17.1", default-features = false }
profiling = { path = "../profiling", optional = true }
sched = { path = "../sched" }
spin = { version = "0.9", default-features = false, features = ["spin_mutex", "rwlock"] }
