[package]
name = "net"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[dependencies]
socket = { path = "../socket" }
smoltcp = { path = "../mygo-smoltcp", default-features = false, features = [
    "alloc",
    "medium-ethernet",
    "medium-ip",
    "proto-ipv4",
    "proto-ipv6",
    "socket-tcp",
    "socket-udp",
    "socket-icmp",
    "socket-raw",
    "socket-dhcpv4",
] }
spin = { version = "0.9", default-features = false, features = ["spin_mutex", "rwlock"] }
# 用于全局 socket 事件唤醒队列（WakeQueue）。
sched = { path = "../sched" }
