[elm]
name = "virtio.framework"
version = "0.1.0"
kind = "service"
source = "kernel-tree:drivers.virtio"
mode = "m"
integrated_phase = "device"

[api]
crate = "virtio"
path = "api"
contract = "driver.virtio.framework@1"
version = "1"

[[profiles]]
id = "hitoshizuku-default"
priority = "100"
