[package]
name = "extfs"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[dependencies]
vfs = { path = "../vfs" }
errno = { path = "../errno" }
log = { path = "../log" }
sched = { path = "../sched" }
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }

[dev-dependencies]
ktest = { path = "../ktest" }
ktest-mock = { path = "../ktest/ktest-mock" }
