[package]
name = "test-kernel-mixin"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test-kernel-mixin"
path = "src/main.rs"
test = false
bench = false

[lib]
name = "test_kernel_mixin"
path = "src/main.rs"
test = false
doctest = false
bench = false

[features]
default = []
elm-integrated = []
replacement = []
reject-migration = ["replacement"]

[dependencies]
elm = { path = "../../../libs/elm", default-features = false, features = ["module", "macros"] }
allocator = { path = "../../../libs/allocator", default-features = false }
general = { path = "../../../general", default-features = false }
log = { path = "../../../libs/log", default-features = false }
sched = { path = "../../../libs/sched", default-features = false }
