[package]
name = "test-kernel-mixin"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test-kernel-mixin"
path = "src/main.rs"
test = false
bench = false

[lib]
name = "test_kernel_mixin"
path = "src/main.rs"
test = false
doctest = false
bench = false

[features]
default = ["elm-lsp"]
elm-lsp = ["allocator/lsp", "general/lsp", "log/lsp", "sched/lsp"]
elm-integrated = []
replacement = []
reject-migration = ["replacement"]

[dependencies]
elm = { path = ".elm/framework/elm", default-features = false, features = ["module", "macros"] }
allocator = { path = ".elm/framework/allocator", default-features = false }
general = { path = ".elm/framework/general", default-features = false }
log = { path = ".elm/framework/log", default-features = false }
sched = { path = ".elm/framework/sched", default-features = false }

[profile.release]
panic = "abort"
codegen-units = 1
lto = false
strip = false

[profile.dev]
panic = "abort"

[workspace]
