#![no_std]

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum Errno {
    ESUCCESS = 0,
    EPERM = 1,
    ENOENT = 2,
    ESRCH = 3,
    EINTR = 4,
    EIO = 5,
    ENXIO = 6,
    E2BIG = 7,
    EAGAIN = 11,
    ECHILD = 10,
    ENOEXEC = 8,
    ENOMEM = 12,
    EACCES = 13,
    EBADF = 9,
    EFAULT = 14,
    EBUSY = 16,
    EEXIST = 17,
    ENODEV = 19,
    ENOTDIR = 20,
    ENOKEY = 126,
    EISDIR = 21,
    EXDEV = 18,
    ENFILE = 23,
    EMFILE = 24,
    EMLINK = 31,
    ENOTTY = 25,
    ETXTBSY = 26,
    EINVAL = 22,
    EFBIG = 27,
    ENOSPC = 28,
    ESPIPE = 29,
    EROFS = 30,
    EPIPE = 32,
    EDOM = 33,
    EDEADLK = 35,
    ERANGE = 34,
    ENAMETOOLONG = 36,
    ENOLCK = 37,
    ENOSYS = 38,
    ENOTEMPTY = 39,
    ELOOP = 40,
    ENOMSG = 42,
    EIDRM = 43,
    ENOSTR = 60,
    ENODATA = 61,
    ETIME = 62,
    ENOSR = 63,
    ENOLINK = 67,
    EPROTO = 71,
    EMULTIHOP = 72,
    EBADMSG = 74,
    EOVERFLOW = 75,
    EILSEQ = 84,
    EOPNOTSUPP = 95,
    EPROTOTYPE = 91,
    ENOPROTOOPT = 92,
    EPROTONOSUPPORT = 93,
    ESOCKTNOSUPPORT = 94,
    EAFNOSUPPORT = 97,
    EADDRINUSE = 98,
    EADDRNOTAVAIL = 99,
    ENETDOWN = 100,
    ENETUNREACH = 101,
    ENETRESET = 102,
    ECONNABORTED = 103,
    ECONNRESET = 104,
    ENOBUFS = 105,
    ENOTSOCK = 88,
    EDESTADDRREQ = 89,
    EMSGSIZE = 90,
    EISCONN = 106,
    ENOTCONN = 107,
    ESHUTDOWN = 108,
    ETIMEDOUT = 110,
    ECONNREFUSED = 111,
    EHOSTUNREACH = 113,
    EALREADY = 114,
    EINPROGRESS = 115,
    ESTALE = 116,
    EDQUOT = 122,
    ECANCELED = 125,
    EOWNERDEAD = 130,
    ENOTRECOVERABLE = 131,
    Other(i32),
}

/// 强制链接器保留错误码转换直接符号目录。
#[doc(hidden)]
pub fn kernel_symbol_catalog_anchor() -> usize {
    Errno::from_i32 as *const () as usize ^ Errno::as_i32 as *const () as usize
}

#[kernel_symbols::export]
impl Errno {
    pub const EWOULDBLOCK: Self = Self::EAGAIN;
    pub const ENOTSUP: Self = Self::EOPNOTSUPP;

    #[kernel_symbols::export(name = "errno.Errno.from_i32", contract = "kernel.errno.conversion@1", version = 1, capabilities = kernel_symbols::capability::CORE_SAFE)]
    pub fn from_i32(code: i32) -> Self {
        match code {
            0 => Errno::ESUCCESS,
            1 => Errno::EPERM,
            2 => Errno::ENOENT,
            3 => Errno::ESRCH,
            4 => Errno::EINTR,
            5 => Errno::EIO,
            6 => Errno::ENXIO,
            7 => Errno::E2BIG,
            8 => Errno::ENOEXEC,
            9 => Errno::EBADF,
            10 => Errno::ECHILD,
            11 => Errno::EAGAIN,
            12 => Errno::ENOMEM,
            13 => Errno::EACCES,
            14 => Errno::EFAULT,
            16 => Errno::EBUSY,
            17 => Errno::EEXIST,
            18 => Errno::EXDEV,
            19 => Errno::ENODEV,
            20 => Errno::ENOTDIR,
            126 => Errno::ENOKEY,
            21 => Errno::EISDIR,
            23 => Errno::ENFILE,
            24 => Errno::EMFILE,
            25 => Errno::ENOTTY,
            26 => Errno::ETXTBSY,
            31 => Errno::EMLINK,
            32 => Errno::EPIPE,
            33 => Errno::EDOM,
            35 => Errno::EDEADLK,
            22 => Errno::EINVAL,
            27 => Errno::EFBIG,
            28 => Errno::ENOSPC,
            29 => Errno::ESPIPE,
            30 => Errno::EROFS,
            34 => Errno::ERANGE,
            36 => Errno::ENAMETOOLONG,
            37 => Errno::ENOLCK,
            38 => Errno::ENOSYS,
            39 => Errno::ENOTEMPTY,
            40 => Errno::ELOOP,
            42 => Errno::ENOMSG,
            43 => Errno::EIDRM,
            60 => Errno::ENOSTR,
            61 => Errno::ENODATA,
            62 => Errno::ETIME,
            63 => Errno::ENOSR,
            67 => Errno::ENOLINK,
            71 => Errno::EPROTO,
            72 => Errno::EMULTIHOP,
            74 => Errno::EBADMSG,
            75 => Errno::EOVERFLOW,
            84 => Errno::EILSEQ,
            88 => Errno::ENOTSOCK,
            89 => Errno::EDESTADDRREQ,
            90 => Errno::EMSGSIZE,
            91 => Errno::EPROTOTYPE,
            92 => Errno::ENOPROTOOPT,
            93 => Errno::EPROTONOSUPPORT,
            94 => Errno::ESOCKTNOSUPPORT,
            95 => Errno::EOPNOTSUPP,
            97 => Errno::EAFNOSUPPORT,
            98 => Errno::EADDRINUSE,
            99 => Errno::EADDRNOTAVAIL,
            100 => Errno::ENETDOWN,
            101 => Errno::ENETUNREACH,
            102 => Errno::ENETRESET,
            103 => Errno::ECONNABORTED,
            104 => Errno::ECONNRESET,
            105 => Errno::ENOBUFS,
            106 => Errno::EISCONN,
            107 => Errno::ENOTCONN,
            108 => Errno::ESHUTDOWN,
            110 => Errno::ETIMEDOUT,
            111 => Errno::ECONNREFUSED,
            113 => Errno::EHOSTUNREACH,
            114 => Errno::EALREADY,
            115 => Errno::EINPROGRESS,
            116 => Errno::ESTALE,
            122 => Errno::EDQUOT,
            125 => Errno::ECANCELED,
            130 => Errno::EOWNERDEAD,
            131 => Errno::ENOTRECOVERABLE,
            other => Errno::Other(other),
        }
    }

    /// 内核常驻代码使用的错误码转换，不经过 ELM 导出包装。
    #[inline(always)]
    pub const fn as_i32_internal(self) -> i32 {
        match self {
            Errno::ESUCCESS => 0,
            Errno::EPERM => 1,
            Errno::ENOENT => 2,
            Errno::ESRCH => 3,
            Errno::EINTR => 4,
            Errno::EIO => 5,
            Errno::ENXIO => 6,
            Errno::E2BIG => 7,
            Errno::ENOEXEC => 8,
            Errno::EAGAIN => 11,
            Errno::ECHILD => 10,
            Errno::ENOMEM => 12,
            Errno::EACCES => 13,
            Errno::EBADF => 9,
            Errno::EFAULT => 14,
            Errno::EBUSY => 16,
            Errno::EEXIST => 17,
            Errno::EXDEV => 18,
            Errno::ENODEV => 19,
            Errno::ENOTDIR => 20,
            Errno::ENOKEY => 126,
            Errno::EISDIR => 21,
            Errno::ENFILE => 23,
            Errno::EMFILE => 24,
            Errno::EMLINK => 31,
            Errno::ENOTTY => 25,
            Errno::ETXTBSY => 26,
            Errno::EINVAL => 22,
            Errno::EFBIG => 27,
            Errno::ENOSPC => 28,
            Errno::ESPIPE => 29,
            Errno::EROFS => 30,
            Errno::EPIPE => 32,
            Errno::EDOM => 33,
            Errno::EDEADLK => 35,
            Errno::ERANGE => 34,
            Errno::ENAMETOOLONG => 36,
            Errno::ENOLCK => 37,
            Errno::ENOSYS => 38,
            Errno::ENOTEMPTY => 39,
            Errno::ELOOP => 40,
            Errno::ENOMSG => 42,
            Errno::EIDRM => 43,
            Errno::ENOSTR => 60,
            Errno::ENODATA => 61,
            Errno::ETIME => 62,
            Errno::ENOSR => 63,
            Errno::ENOLINK => 67,
            Errno::EPROTO => 71,
            Errno::EMULTIHOP => 72,
            Errno::EBADMSG => 74,
            Errno::EOVERFLOW => 75,
            Errno::EILSEQ => 84,
            Errno::ENOTSOCK => 88,
            Errno::EDESTADDRREQ => 89,
            Errno::EMSGSIZE => 90,
            Errno::EPROTOTYPE => 91,
            Errno::ENOPROTOOPT => 92,
            Errno::EPROTONOSUPPORT => 93,
            Errno::ESOCKTNOSUPPORT => 94,
            Errno::EOPNOTSUPP => 95,
            Errno::EAFNOSUPPORT => 97,
            Errno::EADDRINUSE => 98,
            Errno::EADDRNOTAVAIL => 99,
            Errno::ENETDOWN => 100,
            Errno::ENETUNREACH => 101,
            Errno::ENETRESET => 102,
            Errno::ECONNABORTED => 103,
            Errno::ECONNRESET => 104,
            Errno::ENOBUFS => 105,
            Errno::EISCONN => 106,
            Errno::ENOTCONN => 107,
            Errno::ESHUTDOWN => 108,
            Errno::ETIMEDOUT => 110,
            Errno::ECONNREFUSED => 111,
            Errno::EHOSTUNREACH => 113,
            Errno::EALREADY => 114,
            Errno::EINPROGRESS => 115,
            Errno::ESTALE => 116,
            Errno::EDQUOT => 122,
            Errno::ECANCELED => 125,
            Errno::EOWNERDEAD => 130,
            Errno::ENOTRECOVERABLE => 131,
            Errno::Other(code) => code,
        }
    }

    /// 兼容现有内核直调入口。
    #[inline(always)]
    pub const fn as_i32_direct(self) -> i32 {
        self.as_i32_internal()
    }

    #[kernel_symbols::export(name = "errno.Errno.as_i32", contract = "kernel.errno.conversion@1", version = 1, capabilities = kernel_symbols::capability::CORE_SAFE)]
    pub fn as_i32(self) -> i32 {
        self.as_i32_internal()
    }

    pub fn as_usize(self) -> usize {
        (-self.as_i32()) as usize
    }
}

impl From<i32> for Errno {
    fn from(code: i32) -> Self {
        Self::from_i32(code)
    }
}

impl From<Errno> for i32 {
    fn from(errno: Errno) -> Self {
        errno.as_i32()
    }
}

#[cfg(any(test, feature = "ktest-kernel"))]
mod tests;
