#import "../config.typ": appendix-title
#import "../styles/figure.typ": continued-table
#import "../styles/tokens.typ": handoff-fill, soft-fill, stable-fill, warm-fill

= #appendix-title

附录只放查阅型材料。正文各章讨论设计目标、机制边界和工程取舍，附录则保存与源码路径、接口范围和代码句柄直接相关的信息。这样处理可以避免正文被实现细节打断，也能给后续维护者留下较明确的阅读入口。

== A. 代码组织路径

表 附录-1 给出源码阅读时最常用的路径。这里列出的路径只用于帮助定位代码，不作为正文架构原则的替代说明。正文中的分层、信息流和子系统边界仍以各章论述为准。

#continued-table(
  "附录-1",
  [代码组织路径],
  (1.25fr, 2.25fr, 2.2fr),
  (
    table.cell(fill: soft-fill)[#text(weight: "bold")[路径]],
    table.cell(fill: soft-fill)[#text(weight: "bold")[主要内容]],
    table.cell(fill: soft-fill)[#text(weight: "bold")[阅读场景]],
  ),
  (
    [`arch/`],
    [LoongArch64 与 RISC-V64 的入口、异常现场、页表细节、系统调用进入路径和平台指令封装。],
    [排查启动入口、异常处理、架构寄存器、系统调用快路径和页表格式时优先阅读。],

    [`hal/`],
    [把架构侧能力整理为上层可消费的运行期接口，包括用户上下文、调度钩子、用户访问和平台能力注册。],
    [需要理解平台相关能力如何交给通用子系统时阅读。],

    [`general/`],
    [启动上下文、固件视图、系统调用分发、用户地址空间、设备能力、进程间通信和跨子系统公共对象。],
    [阅读平台无关基础设施和跨子系统交接对象时使用。],

    [`kernel/`],
    [内核主入口、系统调用实现、用户程序装载、信号兼容、VFS 适配、设备挂接和运行期编排。],
    [追踪用户态请求如何进入具体内核策略时阅读。],

    [`libs/allocator/`],
    [物理页、Slab 分配器、内核堆和受管堆相关的底层分配能力。],
    [排查内存分配、对象回收和分配失败路径时阅读。],

    [`libs/vfs/`],
    [索引节点、目录项、文件对象、文件描述符表、挂载命名空间、设备文件和套接字文件适配。],
    [追踪文件系统、设备文件、路径解析和文件描述符生命周期时阅读。],

    [`libs/sched/`],
    [任务对象、调度类、运行队列、等待队列、信号状态、凭据、资源限制和任务生命周期。],
    [排查调度、阻塞唤醒、进程关系和信号状态时阅读。],

    [`libs/net/`],
    [网络设备对象、网络栈、接口管理、路由、协议栈适配和网络套接字句柄。],
    [排查网络设备接入、协议推进、套接字状态和路由行为时阅读。],

    [`libs/socket/`],
    [Unix 套接字、内核内存队列、套接字状态和本机进程间通信对象。],
    [排查 Unix 套接字和非网络协议栈的数据路径时阅读。],

    [`libs/errno/`],
    [统一错误码枚举以及错误码和整数返回值之间的转换。],
    [核对系统调用错误返回、兼容层错误码和子系统错误映射时阅读。],

    [`userland/`],
    [用户态根文件系统、辅助脚本、场景文件和随镜像进入用户态的程序资源。],
    [需要确认用户态程序、启动脚本和镜像内容时阅读。],
  ),
  kind: "表",
  continuation-kind: "续表",
  align: (left, left, left),
)

== B. 系统调用和 errno 表

系统调用实现分散在 `kernel/src/syscalls/` 及其调用的通用子系统中。表 附录-2 按 Linux asm-generic 系统调用号列出当前已经接入实际语义路径的入口。这里的“已实现”指调用已经注册到分发表，并且不会直接落入纯 `ENOSYS` 占位实现。对于带 flags、子命令或架构兼容差异的接口，表中的实现范围描述的是当前内核已经支持的部分。

#continued-table(
  "附录-2",
  [已实现系统调用表],
  (0.75fr, 1.55fr, 2.1fr, 3.2fr),
  (
    table.cell(fill: warm-fill)[#text(weight: "bold")[编号]],
    table.cell(fill: warm-fill)[#text(weight: "bold")[ABI 名称]],
    table.cell(fill: warm-fill)[#text(weight: "bold")[内核入口]],
    table.cell(fill: warm-fill)[#text(weight: "bold")[实现范围]],
  ),
  (
    [`17`], [`getcwd`], [`fs::sys_getcwd`], [读取当前工作目录路径。],
    [`19`], [`eventfd2`], [`fs::sys_eventfd2`], [创建事件计数文件描述符。],
    [`20`], [`epoll_create1`], [`fs::sys_epoll_create1`], [创建 epoll 实例。],
    [`21`], [`epoll_ctl`], [`fs::sys_epoll_ctl`], [添加、修改或删除 epoll 监听目标。],
    [`22`], [`epoll_pwait`], [`fs::sys_epoll_pwait`], [等待 epoll 就绪事件并可临时切换信号掩码。],
    [`23`], [`dup`], [`fs::sys_dup`], [复制文件描述符到最小可用编号。],
    [`24`], [`dup3`], [`fs::sys_dup3`], [复制文件描述符到指定编号并设置描述符标志。],
    [`25`], [`fcntl`], [`fs::sys_fcntl`], [执行文件描述符复制、标志、锁和所有权控制。],
    [`29`], [`ioctl`], [`fs::sys_ioctl`], [向文件、设备或套接字发送控制命令。],
    [`30`], [`ioprio_set`], [`fs::sys_ioprio_set`], [设置任务或进程组 I/O 优先级。],
    [`31`], [`ioprio_get`], [`fs::sys_ioprio_get`], [读取任务或进程组 I/O 优先级。],
    [`32`], [`flock`], [`fs::sys_flock`], [处理 BSD 文件锁请求。],
    [`33`], [`mknodat`], [`fs::sys_mknodat`], [创建设备节点或特殊文件。],
    [`34`], [`mkdirat`], [`fs::sys_mkdirat`], [创建目录。],
    [`35`], [`unlinkat`], [`fs::sys_unlinkat`], [删除目录项或目录。],
    [`36`], [`symlinkat`], [`fs::sys_symlinkat`], [创建符号链接。],
    [`37`], [`linkat`], [`fs::sys_linkat`], [创建硬链接。],
    [`38`], [`renameat`], [`fs::sys_renameat`], [重命名路径。],
    [`39`], [`umount2`], [`fs::sys_umount2`], [卸载挂载点。],
    [`40`], [`mount`], [`fs::sys_mount`], [挂载文件系统。],
    [`41`], [`pivot_root`], [`fs::sys_pivot_root`], [切换根挂载布局。],
    [`43`], [`statfs`], [`fs::sys_statfs`], [读取文件系统统计信息。],
    [`44`], [`fstatfs`], [`fs::sys_fstatfs`], [通过文件描述符读取文件系统统计信息。],
    [`45`], [`truncate`], [`fs::sys_truncate`], [按路径截断文件。],
    [`46`], [`ftruncate`], [`fs::sys_ftruncate`], [按文件描述符截断文件。],
    [`47`], [`fallocate`], [`fs::sys_fallocate`], [预分配或调整文件存储范围。],
    [`48`], [`faccessat`], [`fs::sys_faccessat`], [按路径检查访问权限。],
    [`49`], [`chdir`], [`fs::sys_chdir`], [切换当前工作目录。],
    [`50`], [`fchdir`], [`fs::sys_fchdir`], [通过文件描述符切换当前工作目录。],
    [`51`], [`chroot`], [`fs::sys_chroot`], [切换当前根目录。],
    [`52`], [`fchmod`], [`fs::sys_fchmod`], [修改文件描述符目标权限。],
    [`53`], [`fchmodat`], [`fs::sys_fchmodat`], [按路径修改权限。],
    [`54`], [`fchownat`], [`fs::sys_fchownat`], [按路径修改属主。],
    [`55`], [`fchown`], [`fs::sys_fchown`], [修改文件描述符目标属主。],
    [`56`], [`openat`], [`fs::sys_openat`], [相对目录文件描述符打开或创建路径。],
    [`57`], [`close`], [`fs::sys_close`], [关闭文件描述符。],
    [`59`], [`pipe2`], [`fs::sys_pipe2`], [创建管道读写端。],
    [`61`], [`getdents64`], [`fs::sys_getdents64`], [读取目录项序列。],
    [`62`], [`lseek`], [`fs::sys_lseek`], [读取或修改共享文件偏移。],
    [`63`], [`read`], [`fs::sys_read`], [从文件描述符读取数据。],
    [`64`], [`write`], [`fs::sys_write`], [向文件描述符写入数据。],
    [`65`], [`readv`], [`fs::sys_readv`], [按 iovec 分散读取数据。],
    [`66`], [`writev`], [`fs::sys_writev`], [按 iovec 聚集写入数据。],
    [`67`], [`pread64`], [`fs::sys_pread64`], [在指定偏移读取且不改变共享文件偏移。],
    [`68`], [`pwrite64`], [`fs::sys_pwrite64`], [在指定偏移写入且不改变共享文件偏移。],
    [`69`], [`preadv`], [`fs::sys_preadv`], [按 iovec 和指定偏移读取数据。],
    [`70`], [`pwritev`], [`fs::sys_pwritev`], [按 iovec 和指定偏移写入数据。],
    [`71`], [`sendfile`], [`fs::sys_sendfile`], [在两个文件描述符之间搬运数据。],
    [`72`], [`pselect6`], [`fs::sys_pselect6`], [等待 fdset 描述的就绪事件。],
    [`73`], [`ppoll`], [`fs::sys_ppoll`], [等待 poll 描述符集合并可临时切换信号掩码。],
    [`74`], [`signalfd4`], [`fs::sys_signalfd4`], [创建或更新信号文件描述符。],
    [`75`], [`vmsplice`], [`fs::sys_vmsplice`], [把用户 iovec 数据写入管道类目标。],
    [`76`], [`splice`], [`fs::sys_splice`], [在两个文件描述符之间移动数据并维护可选偏移。],
    [`77`], [`tee`], [`fs::sys_tee`], [复制管道类数据流。],
    [`78`], [`readlinkat`], [`fs::sys_readlinkat`], [读取符号链接目标。],
    [`79`], [`fstatat`], [`fs::sys_newfstatat`], [相对路径读取对象元数据。],
    [`80`], [`fstat`], [`fs::sys_fstat`], [读取文件描述符对应对象元数据。],
    [`81`], [`sync`], [`fs::sys_sync`], [触发全局同步。],
    [`82`], [`fsync`], [`fs::sys_fsync`], [同步文件数据和元数据。],
    [`83`], [`fdatasync`], [`fs::sys_fdatasync`], [同步文件数据及必要元数据。],
    [`84`], [`sync_file_range2`], [`fs::sys_sync_file_range2`], [同步文件指定范围。],
    [`85`], [`timerfd_create`], [`fs::sys_timerfd_create`], [创建定时器文件描述符。],
    [`86`], [`timerfd_settime`], [`fs::sys_timerfd_settime`], [设置定时器文件描述符到期时间。],
    [`87`], [`timerfd_gettime`], [`fs::sys_timerfd_gettime`], [读取定时器文件描述符状态。],
    [`88`], [`utimensat`], [`fs::sys_utimensat`], [修改路径时间戳。],
    [`90`], [`capget`], [`process::sys_capget`], [读取当前任务能力集合。],
    [`91`], [`capset`], [`process::sys_capset`], [设置当前任务能力集合。],
    [`92`], [`personality`], [`process::sys_personality`], [读取或设置进程 personality 标志。],
    [`93`], [`exit`], [`process::sys_exit`], [终止当前任务并进入退出回收路径。],
    [`94`], [`exit_group`], [`process::sys_exit_group`], [终止当前线程组并唤醒等待者。],
    [`95`], [`waitid`], [`process::sys_waitid`], [按 waitid 语义等待子任务状态变化。],
    [`96`], [`set_tid_address`], [`process::sys_set_tid_address`], [登记线程退出时清零并唤醒的用户地址。],
    [`98`], [`futex`], [`process::sys_futex`], [执行传统 futex 等待、唤醒和重排队操作。],
    [`99`], [`set_robust_list`], [`process::sys_set_robust_list`], [登记 robust futex 链表头。],
    [`100`], [`get_robust_list`], [`process::sys_get_robust_list`], [读取目标线程的 robust futex 链表头。],
    [`101`], [`nanosleep`], [`process::sys_nanosleep`], [按相对时间睡眠并在被中断时返回剩余时间。],
    [`102`], [`getitimer`], [`process::sys_getitimer`], [读取进程 interval timer 状态。],
    [`103`], [`setitimer`], [`process::sys_setitimer`], [设置进程 interval timer 状态。],
    [`112`], [`clock_settime`], [`process::sys_clock_settime`], [设置本内核支持的墙钟时间。],
    [`113`], [`clock_gettime`], [`process::sys_clock_gettime`], [读取指定时钟的当前时间。],
    [`114`], [`clock_getres`], [`process::sys_clock_getres`], [读取指定时钟分辨率。],
    [`115`], [`clock_nanosleep`], [`process::sys_clock_nanosleep`], [按指定时钟执行相对或绝对睡眠。],
    [`116`], [`syslog`], [`syslog::sys_syslog`], [读取或控制内核日志缓冲区的兼容入口。],
    [`117`], [`ptrace`], [`process::sys_ptrace`], [支持追踪附加、继续、分离、中断等 ptrace 控制路径。],
    [`118`], [`sched_setparam`], [`process::sys_sched_setparam`], [设置调度参数。],
    [`119`], [`sched_setscheduler`], [`process::sys_sched_setscheduler`], [设置调度策略和参数。],
    [`120`], [`sched_getscheduler`], [`process::sys_sched_getscheduler`], [读取调度策略。],
    [`121`], [`sched_getparam`], [`process::sys_sched_getparam`], [读取调度参数。],
    [`122`], [`sched_setaffinity`], [`process::sys_sched_setaffinity`], [设置 CPU 亲和性掩码。],
    [`123`], [`sched_getaffinity`], [`process::sys_sched_getaffinity`], [读取 CPU 亲和性掩码。],
    [`124`], [`sched_yield`], [`process::sys_sched_yield`], [当前任务主动让出处理器。],
    [`125`], [`sched_get_priority_max`], [`process::sys_sched_get_priority_max`], [读取调度策略最大优先级。],
    [`126`], [`sched_get_priority_min`], [`process::sys_sched_get_priority_min`], [读取调度策略最小优先级。],
    [`127`], [`sched_rr_get_interval`], [`process::sys_sched_rr_get_interval`], [读取轮转调度时间片。],
    [`128`], [`restart_syscall`], [`signal::sys_restart_syscall`], [保留可重启系统调用兼容入口，当前返回 `EINTR`。],
    [`129`], [`kill`], [`process::sys_kill`], [向进程或进程组投递信号。],
    [`130`], [`tkill`], [`process::sys_tkill`], [向指定线程投递信号。],
    [`131`], [`tgkill`], [`process::sys_tgkill`], [向指定线程组中的线程投递信号。],
    [`132`], [`sigaltstack`], [`signal::sys_sigaltstack`], [设置或读取备用信号栈。],
    [`133`], [`rt_sigsuspend`], [`signal::sys_rt_sigsuspend`], [临时替换信号屏蔽字并等待信号。],
    [`134`], [`rt_sigaction`], [`signal::sys_rt_sigaction`], [安装或读取信号处理动作。],
    [`135`], [`rt_sigprocmask`], [`signal::sys_rt_sigprocmask`], [修改或读取线程信号屏蔽字。],
    [`136`], [`rt_sigpending`], [`signal::sys_rt_sigpending`], [读取当前挂起信号集合。],
    [`137`], [`rt_sigtimedwait`], [`signal::sys_rt_sigtimedwait`], [限时等待指定信号集合。],
    [`138`], [`rt_sigqueueinfo`], [`signal::sys_rt_sigqueueinfo`], [携带 siginfo 投递信号。],
    [`139`], [`rt_sigreturn`], [`signal::sys_rt_sigreturn`], [从用户信号帧恢复陷阱帧。],
    [`140`], [`setpriority`], [`process::sys_setpriority`], [设置 nice 优先级。],
    [`141`], [`getpriority`], [`process::sys_getpriority`], [读取 nice 优先级。],
    [`142`], [`reboot`], [`process::sys_reboot`], [处理关机、重启和重启命令的特权入口。],
    [`143`], [`setregid`], [`process::sys_setregid`], [设置真实和有效组标识。],
    [`144`], [`setgid`], [`process::sys_setgid`], [设置组标识。],
    [`145`], [`setreuid`], [`process::sys_setreuid`], [设置真实和有效用户标识。],
    [`146`], [`setuid`], [`process::sys_setuid`], [设置用户标识。],
    [`147`], [`setresuid`], [`process::sys_setresuid`], [设置真实、有效和保存用户标识。],
    [`148`], [`getresuid`], [`process::sys_getresuid`], [读取真实、有效和保存用户标识。],
    [`149`], [`setresgid`], [`process::sys_setresgid`], [设置真实、有效和保存组标识。],
    [`150`], [`getresgid`], [`process::sys_getresgid`], [读取真实、有效和保存组标识。],
    [`151`], [`setfsuid`], [`process::sys_setfsuid`], [设置文件系统用户标识。],
    [`152`], [`setfsgid`], [`process::sys_setfsgid`], [设置文件系统组标识。],
    [`153`], [`times`], [`process::sys_times`], [读取任务累计运行时间。],
    [`154`], [`setpgid`], [`process::sys_setpgid`], [设置进程组关系。],
    [`155`], [`getpgid`], [`process::sys_getpgid`], [读取进程组标识。],
    [`156`], [`getsid`], [`process::sys_getsid`], [读取会话标识。],
    [`157`], [`setsid`], [`process::sys_setsid`], [创建新会话并成为会话首进程。],
    [`158`], [`getgroups`], [`process::sys_getgroups`], [读取附属组列表。],
    [`159`], [`setgroups`], [`process::sys_setgroups`], [设置附属组列表。],
    [`160`], [`uname`], [`process::sys_uname`], [读取 UTS 系统信息。],
    [`161`], [`sethostname`], [`process::sys_sethostname`], [设置 UTS 主机名。],
    [`162`], [`setdomainname`], [`process::sys_setdomainname`], [设置 UTS 域名。],
    [`163`], [`getrlimit`], [`process::sys_getrlimit`], [读取资源限制。],
    [`164`], [`setrlimit`], [`process::sys_setrlimit`], [设置资源限制。],
    [`165`], [`getrusage`], [`process::sys_getrusage`], [读取任务或子任务资源用量。],
    [`166`], [`umask`], [`process::sys_umask`], [设置并返回旧文件创建权限屏蔽字。],
    [`167`], [`prctl`], [`process::sys_prctl`], [处理进程控制命令中已接入的兼容子集。],
    [`168`], [`getcpu`], [`process::sys_getcpu`], [读取当前 CPU 和 NUMA 节点兼容信息。],
    [`169`], [`gettimeofday`], [`process::sys_gettimeofday`], [读取兼容 timeval 形式的墙钟时间。],
    [`170`], [`settimeofday`], [`process::sys_settimeofday`], [设置兼容 timeval 形式的墙钟时间。],
    [`172`], [`getpid`], [`process::sys_getpid`], [读取进程标识。],
    [`173`], [`getppid`], [`process::sys_getppid`], [读取父进程标识。],
    [`174`], [`getuid`], [`process::sys_getuid`], [读取真实用户标识。],
    [`175`], [`geteuid`], [`process::sys_geteuid`], [读取有效用户标识。],
    [`176`], [`getgid`], [`process::sys_getgid`], [读取真实组标识。],
    [`177`], [`getegid`], [`process::sys_getegid`], [读取有效组标识。],
    [`178`], [`gettid`], [`process::sys_gettid`], [读取线程标识。],
    [`179`], [`sysinfo`], [`process::sys_sysinfo`], [读取系统内存和负载概要信息。],
    [`194`], [`shmget`], [`ipc::sys_shmget`], [创建或查找 System V 共享内存段。],
    [`195`], [`shmctl`], [`ipc::sys_shmctl`], [查询、修改或删除 System V 共享内存段。],
    [`196`], [`shmat`], [`ipc::sys_shmat`], [把共享内存段附加到当前地址空间。],
    [`197`], [`shmdt`], [`ipc::sys_shmdt`], [从当前地址空间分离共享内存段。],
    [`198`], [`socket`], [`fs::sys_socket`], [创建套接字文件描述符。],
    [`199`], [`socketpair`], [`fs::sys_socketpair`], [创建一对已连接本地套接字。],
    [`200`], [`bind`], [`fs::sys_bind`], [绑定套接字本地地址。],
    [`201`], [`listen`], [`fs::sys_listen`], [把流式套接字切换到监听状态。],
    [`202`], [`accept`], [`fs::sys_accept`], [接受监听队列中的连接。],
    [`203`], [`connect`], [`fs::sys_connect`], [发起连接或设置默认远端地址。],
    [`204`], [`getsockname`], [`fs::sys_getsockname`], [读取套接字本地地址。],
    [`205`], [`getpeername`], [`fs::sys_getpeername`], [读取套接字对端地址。],
    [`206`], [`sendto`], [`fs::sys_sendto`], [向套接字发送数据并可指定目标地址。],
    [`207`], [`recvfrom`], [`fs::sys_recvfrom`], [从套接字接收数据并可返回来源地址。],
    [`208`], [`setsockopt`], [`fs::sys_setsockopt`], [设置套接字选项。],
    [`209`], [`getsockopt`], [`fs::sys_getsockopt`], [读取套接字选项。],
    [`210`], [`shutdown`], [`fs::sys_shutdown`], [关闭套接字读端、写端或双向通信。],
    [`211`], [`sendmsg`], [`fs::sys_sendmsg`], [按消息头发送分散缓冲区和控制信息。],
    [`212`], [`recvmsg`], [`fs::sys_recvmsg`], [按消息头接收数据和控制信息。],
    [`213`], [`readahead`], [`fs::sys_readahead`], [向文件对象提交预读提示。],
    [`214`], [`brk`], [`mm::sys_brk`], [调整传统用户堆顶。],
    [`215`], [`munmap`], [`mm::sys_munmap`], [解除用户虚拟内存映射。],
    [`216`], [`mremap`], [`mm::sys_mremap`], [调整或移动既有映射。],
    [`220`], [`clone`], [`process::sys_clone`], [按共享标志创建进程或线程。],
    [`221`], [`execve`], [`process::sys_execve`], [替换当前进程的用户态映像。],
    [`222`], [`mmap`], [`mm::sys_mmap`], [建立匿名或文件后备用户映射。],
    [`223`], [`fadvise64`], [`fs::sys_fadvise64`], [提交文件访问模式提示。],
    [`226`], [`mprotect`], [`mm::sys_mprotect`], [修改用户映射权限。],
    [`227`], [`msync`], [`mm::sys_msync`], [同步用户映射对应的后备对象。],
    [`228`], [`mlock`], [`mm::sys_mlock`], [锁定用户内存范围的兼容入口。],
    [`229`], [`munlock`], [`mm::sys_munlock`], [解除用户内存范围锁定的兼容入口。],
    [`230`], [`mlockall`], [`mm::sys_mlockall`], [锁定当前地址空间映射的兼容入口。],
    [`231`], [`munlockall`], [`mm::sys_munlockall`], [解除地址空间映射锁定的兼容入口。],
    [`232`], [`mincore`], [`mm::sys_mincore`], [查询用户地址范围的驻留状态。],
    [`233`], [`madvise`], [`mm::sys_madvise`], [接收用户映射访问建议。],
    [`240`], [`rt_tgsigqueueinfo`], [`process::sys_rt_tgsigqueueinfo`], [向指定线程携带 siginfo 投递信号。],
    [`242`], [`accept4`], [`fs::sys_accept4`], [接受连接并设置新描述符标志。],
    [`243`], [`recvmmsg`], [`fs::sys_recvmmsg`], [批量接收多个消息。],
    [`260`], [`wait4`], [`process::sys_wait4`], [等待子任务状态变化并回收退出任务。],
    [`261`], [`prlimit64`], [`process::sys_prlimit64`], [读取或设置目标任务资源限制。],
    [`267`], [`syncfs`], [`fs::sys_syncfs`], [同步指定文件描述符所在文件系统。],
    [`269`], [`sendmmsg`], [`fs::sys_sendmmsg`], [批量发送多个消息。],
    [`272`], [`kcmp`], [`process::sys_kcmp`], [比较两个任务之间的文件、地址空间或共享对象关系。],
    [`274`], [`sched_setattr`], [`process::sys_sched_setattr`], [按 sched_attr 设置调度属性。],
    [`275`], [`sched_getattr`], [`process::sys_sched_getattr`], [按 sched_attr 读取调度属性。],
    [`276`], [`renameat2`], [`fs::sys_renameat2`], [带扩展标志的重命名路径。],
    [`278`], [`getrandom`], [`process::sys_getrandom`], [从内核随机源填充用户缓冲区。],
    [`279`], [`memfd_create`], [`fs::sys_memfd_create`], [创建匿名内存文件。],
    [`281`], [`execveat`], [`process::sys_execveat`], [相对目录文件描述符执行程序替换。],
    [`283`], [`membarrier`], [`process::sys_membarrier`], [处理内存屏障能力查询和全局屏障请求。],
    [`284`], [`mlock2`], [`mm::sys_mlock2`], [带 flags 的 mlock 兼容入口。],
    [`285`], [`copy_file_range`], [`fs::sys_copy_file_range`], [在两个文件描述符之间复制指定范围。],
    [`286`], [`preadv2`], [`fs::sys_preadv2`], [带 RWF 标志的向量读取入口。],
    [`287`], [`pwritev2`], [`fs::sys_pwritev2`], [带 RWF 标志的向量写入入口。],
    [`291`], [`statx`], [`fs::sys_statx`], [读取扩展文件元数据。],
    [`293`], [`rseq`], [`process::sys_rseq`], [登记或注销 restartable sequences 控制块。],
    [`403`], [`clock_gettime64`], [`process::sys_clock_gettime64`], [time64 形式的 clock_gettime 入口。],
    [`404`], [`clock_settime64`], [`process::sys_clock_settime64`], [time64 形式的 clock_settime 入口。],
    [`406`], [`clock_getres_time64`], [`process::sys_clock_getres_time64`], [time64 形式的 clock_getres 入口。],
    [`407`], [`clock_nanosleep_time64`], [`process::sys_clock_nanosleep_time64`], [time64 形式的 clock_nanosleep 入口。],
    [`410`], [`timerfd_gettime64`], [`fs::sys_timerfd_gettime64`], [time64 形式的 timerfd_gettime 入口。],
    [`411`], [`timerfd_settime64`], [`fs::sys_timerfd_settime64`], [time64 形式的 timerfd_settime 入口。],
    [`412`], [`utimensat_time64`], [`fs::sys_utimensat_time64`], [time64 形式的 utimensat 入口。],
    [`413`], [`pselect6_time64`], [`fs::sys_pselect6_time64`], [time64 形式的 pselect6 入口。],
    [`414`], [`ppoll_time64`], [`fs::sys_ppoll_time64`], [time64 形式的 ppoll 入口。],
    [`417`], [`recvmmsg_time64`], [`fs::sys_recvmmsg_time64`], [time64 形式的 recvmmsg 入口。],
    [`421`], [`rt_sigtimedwait_time64`], [`signal::sys_rt_sigtimedwait_time64`], [time64 形式的 rt_sigtimedwait 入口。],
    [`422`], [`futex_time64`], [`process::sys_futex`], [time64 形式的传统 futex 入口。],
    [`423`], [`sched_rr_get_interval_time64`], [`process::sys_sched_rr_get_interval`], [time64 形式的轮转时间片查询入口。],
    [`424`], [`pidfd_send_signal`], [`signal::sys_pidfd_send_signal`], [通过 pid 文件描述符向目标任务投递信号。],
    [`434`], [`pidfd_open`], [`process::sys_pidfd_open`], [为目标任务创建 pid 文件描述符。],
    [`435`], [`clone3`], [`process::sys_clone3`], [按 clone3 参数块创建进程或线程。],
    [`436`], [`close_range`], [`fs::sys_close_range`], [批量关闭或设置一段文件描述符。],
    [`437`], [`openat2`], [`fs::sys_openat2`], [按 open_how 参数块打开路径。],
    [`438`], [`pidfd_getfd`], [`fs::sys_pidfd_getfd`], [通过 pid 文件描述符复制目标任务文件描述符。],
    [`439`], [`faccessat2`], [`fs::sys_faccessat2`], [带 flags 的路径访问权限检查。],
    [`441`], [`epoll_pwait2`], [`fs::sys_epoll_pwait2`], [使用 timespec 超时的 epoll 等待入口。],
    [`449`], [`futex_waitv`], [`process::sys_futex_waitv`], [等待多个 futex 条件之一满足。],
    [`452`], [`fchmodat2`], [`fs::sys_fchmodat2`], [带 flags 的路径权限修改入口。],
    [`454`], [`futex_wake`], [`process::sys_futex_wake`], [futex2 唤醒入口。],
    [`455`], [`futex_wait`], [`process::sys_futex_wait`], [futex2 等待入口。],
    [`456`], [`futex_requeue`], [`process::sys_futex_requeue`], [futex2 重排队入口。],
    [`510`], [`mygo_sched_info`], [`process::sys_mygo_sched_info`], [读取内核私有调度诊断信息。],
  ),
  kind: "表",
  continuation-kind: "续表",
  align: (left, left, left, left),
)

表 附录-3 整理 POSIX `errno` 名称。该表列名称和语义，不列数值，因为具体整数值可能受平台 ABI 影响。当前内核是否已经完整产生这些错误码，仍以 `libs/errno/src/lib.rs` 和具体系统调用实现为准。

#continued-table(
  "附录-3",
  [POSIX errno 表],
  (1.15fr, 1.65fr, 2.65fr),
  (
    table.cell(fill: handoff-fill)[#text(weight: "bold")[错误码]],
    table.cell(fill: handoff-fill)[#text(weight: "bold")[POSIX 语义]],
    table.cell(fill: handoff-fill)[#text(weight: "bold")[中文说明]],
  ),
  (
    [`E2BIG`],
    [Argument list too long],
    [参数列表过长。],

    [`EACCES`],
    [Permission denied],
    [权限检查拒绝访问。],

    [`EADDRINUSE`],
    [Address in use],
    [地址或端口已经被占用。],

    [`EADDRNOTAVAIL`],
    [Address not available],
    [请求的本地地址不可用。],

    [`EAFNOSUPPORT`],
    [Address family not supported],
    [地址族不被支持。],

    [`EAGAIN`],
    [Resource unavailable, try again],
    [资源暂时不可用，调用方可以稍后重试。],

    [`EALREADY`],
    [Connection already in progress],
    [连接操作已经在进行中。],

    [`EBADF`],
    [Bad file descriptor],
    [文件描述符无效。],

    [`EBADMSG`],
    [Bad message],
    [消息格式或内容无效。],

    [`EBUSY`],
    [Device or resource busy],
    [设备或资源正忙。],

    [`ECANCELED`],
    [Operation canceled],
    [操作被取消。],

    [`ECHILD`],
    [No child processes],
    [没有可等待的子进程。],

    [`ECONNABORTED`],
    [Connection aborted],
    [连接被中止。],

    [`ECONNREFUSED`],
    [Connection refused],
    [连接请求被拒绝。],

    [`ECONNRESET`],
    [Connection reset],
    [连接被重置。],

    [`EDEADLK`],
    [Resource deadlock would occur],
    [操作会导致资源死锁。],

    [`EDESTADDRREQ`],
    [Destination address required],
    [需要提供目标地址。],

    [`EDOM`],
    [Mathematics argument out of domain of function],
    [数学函数参数超出定义域。],

    [`EDQUOT`],
    [Reserved],
    [POSIX 保留错误名，传统语义通常表示磁盘配额耗尽。],

    [`EEXIST`],
    [File exists],
    [目标文件、目录或命名对象已存在。],

    [`EFAULT`],
    [Bad address],
    [用户地址或指针无效。],

    [`EFBIG`],
    [File too large],
    [文件过大。],

    [`EHOSTUNREACH`],
    [Host is unreachable],
    [目标主机不可达。],

    [`EIDRM`],
    [Identifier removed],
    [IPC 标识符已经被移除。],

    [`EILSEQ`],
    [Illegal byte sequence],
    [非法字节序列。],

    [`EINPROGRESS`],
    [Operation in progress],
    [操作正在进行中。],

    [`EINTR`],
    [Interrupted function],
    [函数调用被信号中断。],

    [`EINVAL`],
    [Invalid argument],
    [参数无效。],

    [`EIO`],
    [I/O error],
    [输入输出错误。],

    [`EISCONN`],
    [Socket is connected],
    [套接字已经连接。],

    [`EISDIR`],
    [Is a directory],
    [目标是目录。],

    [`ELOOP`],
    [Too many levels of symbolic links],
    [符号链接层级过多。],

    [`EMFILE`],
    [File descriptor value too large],
    [进程打开的文件描述符数量达到限制。],

    [`EMLINK`],
    [Too many links],
    [链接数过多。],

    [`EMSGSIZE`],
    [Message too large],
    [消息过大。],

    [`EMULTIHOP`],
    [Reserved],
    [POSIX 保留错误名，传统语义通常表示多跳链路错误。],

    [`ENAMETOOLONG`],
    [Filename too long],
    [文件名或路径名过长。],

    [`ENETDOWN`],
    [Network is down],
    [网络不可用。],

    [`ENETRESET`],
    [Connection aborted by network],
    [连接被网络侧中止。],

    [`ENETUNREACH`],
    [Network unreachable],
    [网络不可达。],

    [`ENFILE`],
    [Too many files open in system],
    [系统范围内打开文件数量达到限制。],

    [`ENOBUFS`],
    [No buffer space available],
    [缓冲区空间不足。],

    [`ENODATA`],
    [No message is available on the stream head read queue],
    [流首读队列中没有可用消息。],

    [`ENODEV`],
    [No such device],
    [没有对应设备。],

    [`ENOENT`],
    [No such file or directory],
    [没有对应文件或目录。],

    [`ENOEXEC`],
    [Executable file format error],
    [可执行文件格式错误。],

    [`ENOLCK`],
    [No locks available],
    [没有可用锁。],

    [`ENOLINK`],
    [Reserved],
    [POSIX 保留错误名，传统语义通常表示链路断开。],

    [`ENOMEM`],
    [Not enough space],
    [内存或地址空间不足。],

    [`ENOMSG`],
    [No message of the desired type],
    [没有所需类型的消息。],

    [`ENOPROTOOPT`],
    [Protocol not available],
    [协议选项不可用。],

    [`ENOSPC`],
    [No space left on device],
    [设备或文件系统空间不足。],

    [`ENOSR`],
    [No stream resources],
    [流资源不足。],

    [`ENOSTR`],
    [Not a stream],
    [对象不是流。],

    [`ENOSYS`],
    [Functionality not supported],
    [功能不被支持。],

    [`ENOTCONN`],
    [The socket is not connected],
    [套接字尚未连接。],

    [`ENOTDIR`],
    [Not a directory],
    [路径组件不是目录。],

    [`ENOTEMPTY`],
    [Directory not empty],
    [目录非空。],

    [`ENOTRECOVERABLE`],
    [State not recoverable],
    [互斥量保护状态不可恢复。],

    [`ENOTSOCK`],
    [Not a socket],
    [对象不是套接字。],

    [`ENOTSUP`],
    [Not supported],
    [操作不被支持。],

    [`ENOTTY`],
    [Inappropriate I/O control operation],
    [不适合的输入输出控制操作。],

    [`ENXIO`],
    [No such device or address],
    [没有对应设备或地址。],

    [`EOPNOTSUPP`],
    [Operation not supported on socket],
    [套接字不支持该操作。],

    [`EOVERFLOW`],
    [Value too large to be stored in data type],
    [数值过大，无法存入目标数据类型。],

    [`EOWNERDEAD`],
    [Previous owner died],
    [健壮互斥量的前一个拥有者已经终止。],

    [`EPERM`],
    [Operation not permitted],
    [操作不被允许。],

    [`EPIPE`],
    [Broken pipe],
    [管道或套接字对端已经关闭。],

    [`EPROTO`],
    [Protocol error],
    [协议错误。],

    [`EPROTONOSUPPORT`],
    [Protocol not supported],
    [协议不被支持。],

    [`EPROTOTYPE`],
    [Protocol wrong type for socket],
    [套接字协议类型不匹配。],

    [`ERANGE`],
    [Result too large],
    [结果超出可表示范围。],

    [`EROFS`],
    [Read-only file system],
    [只读文件系统。],

    [`ESPIPE`],
    [Invalid seek],
    [无效定位操作。],

    [`ESRCH`],
    [No such process],
    [没有对应进程。],

    [`ESTALE`],
    [Reserved],
    [POSIX 保留错误名，传统语义通常表示陈旧文件句柄。],

    [`ETIME`],
    [Stream ioctl() timeout],
    [流控制操作超时。],

    [`ETIMEDOUT`],
    [Connection timed out],
    [连接超时。],

    [`ETXTBSY`],
    [Text file busy],
    [文本文件正忙。],

    [`EWOULDBLOCK`],
    [Operation would block],
    [操作会阻塞。该错误码可以与 `EAGAIN` 取相同值。],

    [`EXDEV`],
    [Cross-device link],
    [跨设备链接或重命名。],
  ),
  kind: "表",
  continuation-kind: "续表",
  align: (left, left, left),
)

== C. 核心概念与代码句柄对照

正文优先使用中文概念。需要回到源码时，表 附录-4 可以作为概念和代码句柄之间的索引。表中列出的代码句柄均应在正文中使用反引号表示。

#continued-table(
  "附录-4",
  [核心概念与代码句柄对照],
  (1.25fr, 1.55fr, 2.4fr),
  (
    table.cell(fill: stable-fill)[#text(weight: "bold")[中文概念]],
    table.cell(fill: stable-fill)[#text(weight: "bold")[代码句柄]],
    table.cell(fill: stable-fill)[#text(weight: "bold")[主要位置]],
  ),
  (
    [启动上下文],
    [`StartContext`],
    [`general/src/start.rs`。启动阶段整理固件、内存、命令行和架构交接信息。],

    [系统调用上下文],
    [`SyscallContext`],
    [`general/src/syscall.rs`。系统调用分发时保存任务、参数、返回值和陷阱帧访问入口。],

    [陷阱帧],
    [`TrapFrame`],
    [`arch/src/riscv64/trap_frame.rs` 与 `arch/src/loongarch64/specific.rs`。保存用户态寄存器和异常现场。],

    [设备能力],
    [`DeviceFunction`],
    [`general/src/dev/function.rs`。设备向内核发布的统一能力边界。],

    [字符设备对象],
    [`CharDevice`],
    [`general/src/dev/char.rs`。字符流设备和终端后端的类型化对象。],

    [块设备对象],
    [`BlockDevice`],
    [`general/src/dev/block.rs`。块请求提交、同步等待和设备几何信息的类型化对象。],

    [网络设备对象],
    [`NetDevice`],
    [`libs/net/src/device.rs`。网络接口身份、链路状态、MTU 和收发统计的承载对象。],

    [实时时钟设备],
    [`RtcDevice`],
    [`general/src/dev/rtc.rs`。时间读写、告警和周期中断相关能力。],

    [文件操作接口],
    [`FileOps`],
    [`libs/vfs/src/file.rs`。读写、控制、轮询和关闭等文件行为入口。],

    [文件描述符表],
    [`FdTable`],
    [`libs/vfs/src/fdtable.rs`。文件描述符到文件对象的映射和执行时关闭标志管理。],

    [用户虚拟地址空间],
    [`VmSpace`],
    [`general/src/mm/vm_space.rs`。VMA、缺页、映射、权限变更和执行装载相关地址空间操作。],

    [任务对象],
    [`Task`],
    [`libs/sched/src/task.rs`。任务身份、调度状态、信号状态、凭据和资源视图。],

    [网络栈],
    [`NetStack`],
    [`libs/net/src/stack.rs`。接口注册表、路由、协议栈推进和网络套接字管理。],

    [网络套接字状态],
    [`SocketState`],
    [`libs/net/src/socket.rs`。网络套接字连接、监听、收发和关闭状态。],

    [Unix 套接字对象],
    [`Socket`],
    [`libs/socket/src/state.rs`。本机 Unix 套接字的连接和内存队列状态。],

    [统一错误码],
    [`Errno`],
    [`libs/errno/src/lib.rs`。内核内部错误和用户态负 errno 返回值之间的统一枚举。],
  ),
  kind: "表",
  continuation-kind: "续表",
  align: (left, left, left),
)
