[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[features]
bench = []
block-bench = []
allocator-bench = []
embedded-initramfs = []
trace-task-lifecycle = ["sched/trace-task-lifecycle"]
allocator-tests = [
    "ktest/kernel",
    "allocator/ktest-kernel",
]
kernel-tests = [
    "ktest/kernel",
    "errno/ktest-kernel",
    "elf/ktest-kernel",
    "mm/ktest-kernel",
    "log/ktest-kernel",
    "allocator/ktest-kernel",
]

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
acpi = { path = "../libs/acpi", default-features = false, features = ["aml", "alloc"] }
elf = { path = "../libs/elf" }
errno = { path = "../libs/errno" }
extfs = { path = "../libs/extfs" }
fatfs = { path = "../libs/fatfs" }
general = { path = "../general" }
ktest = { path = "../libs/ktest" }
log = { path = "../libs/log" }
allocator ={ path = "../libs/allocator" }
hal = { path = "../hal" }
mm = { path = "../libs/mm" }
net = { path = "../libs/net" }
sched = { path = "../libs/sched" }
vfs = { path = "../libs/vfs" }
