[package]
name = "sched"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[features]
trace-task-lifecycle = []
performance-profile = ["dep:profiling"]
syscall-model-markers = ["performance-profile", "profiling/syscall-model-markers"]

[dependencies]
errno = { path = "../errno" }
kernel-symbols = { path = "../kernel-symbols" }
log = { path = "../log" }
profiling = { path = "../profiling", optional = true }

[dev-dependencies]
ktest = { path = "../ktest" }
