[elm]
name = "platform.ls7a-rtc"
version = "0.1.0"
kind = "driver"
source = "kernel-tree:drivers.ls7a-rtc"
mode = "m"
integrated_phase = "device"

[[profiles]]
id = "hitoshizuku-default"
priority = "100"
