[package]
name = "elm"
version.workspace = true
edition.workspace = true

[lib]
test = true
doctest = false
bench = false

[features]
default = []

[dependencies]
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["alloc", "zeroize"] }

[dev-dependencies]
ed25519-dalek = { version = "2.2.0", features = ["zeroize"] }
