[package]
name = "elm"
version.workspace = true
edition.workspace = true

[lib]
test = true
doctest = false
bench = false

[features]
default = ["runtime-model", "macros"]
runtime-model = ["dep:ed25519-dalek"]
module = []
macros = ["dep:elm-macros"]

[dependencies]
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["alloc", "zeroize"], optional = true }
elm-macros = { path = "macros", optional = true }

[dev-dependencies]
ed25519-dalek = { version = "2.2.0", features = ["zeroize"] }
