[package]
name = "allocator"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doctest = false
bench = false

[features]
ktest-kernel = ["ktest/kernel"]
track-allocations = []
performance-profile = []

[dependencies]
log = { path = "../log" }
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }
ktest = { path = "../ktest", optional = true }
kernel-symbols = { path = "../kernel-symbols" }
