[package]
name = "arch"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[features]
performance-profile = ["dep:profiling"]
syscall-model-markers = ["performance-profile", "profiling/syscall-model-markers", "sched/syscall-model-markers"]

[dependencies]
general = { path = "../general" }
allocator = { path = "../libs/allocator" }
efi = { path = "../libs/efi" }
fdt = { path = "../libs/fdt", features = ["alloc"] }
log = { path = "../libs/log" }
mm = { path = "../libs/mm" }
native-abi = { path = "../libs/native-abi" }
profiling = { path = "../libs/profiling", optional = true }
sched = { path = "../libs/sched" }
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }
