[package]
name = "log"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[features]
ktest-kernel = ["ktest/kernel"]

[dependencies]
ktest = { path = "../ktest", optional = true }
kernel-symbols = { path = "../kernel-symbols" }

[dev-dependencies]
ktest = { path = "../ktest" }
