[package]
name = "mm"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = false
bench = false

[features]
ktest-kernel = ["ktest/kernel"]

[dependencies]
errno = { path = "../errno" }
kernel-symbols = { path = "../kernel-symbols" }
log = { path = "../log" }
ktest = { path = "../ktest", optional = true }

[dev-dependencies]
ktest = { path = "../ktest" }
