#!/bin/sh
# Run the common cold BuildStorm profile flow with a Linux guest kernel.
set -eu

repo=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)

PROFILE_BOOT_MODE=linux
PROFILE_SYSTEM=${PROFILE_SYSTEM:-linux}
PROFILE_KERNEL=${PROFILE_KERNEL:-"$repo/build/linux/vmlinux"}
PROFILE_LINUX_INITRAMFS=${PROFILE_LINUX_INITRAMFS:-"$repo/build/loongarch64/compat-initramfs.cpio"}
PROFILE_SYMBOL_MAP=${PROFILE_SYMBOL_MAP:-"$repo/build/linux/System.map"}
PROFILE_SYMBOL_MANIFEST=${PROFILE_SYMBOL_MANIFEST:-"$PROFILE_SYMBOL_MAP.manifest"}
PROFILE_REQUIRE_SYMBOL_MANIFEST=${PROFILE_REQUIRE_SYMBOL_MANIFEST:-1}
PROFILE_QEMU_OBSERVER=${PROFILE_QEMU_OBSERVER:-1}
PROFILE_CAPTURE=${PROFILE_CAPTURE:-0}

export PROFILE_BOOT_MODE PROFILE_SYSTEM PROFILE_KERNEL PROFILE_LINUX_INITRAMFS
export PROFILE_SYMBOL_MAP PROFILE_SYMBOL_MANIFEST PROFILE_REQUIRE_SYMBOL_MANIFEST
export PROFILE_QEMU_OBSERVER PROFILE_CAPTURE

exec "$repo/scripts/buildstorm-profile-host.sh" "$@"
