[build]
rustflags = [
    "--cfg=elm_kernel_api=\"contest-2026\"",
    "--check-cfg=cfg(elm_kernel_api,values(\"contest-2026\"))",
    "--cfg=elm_kernel_profile=\"035f323b73bf4db169bc1d69e615f0a5f7c35393a5d2d0055895c289e27ae384\"",
    "--check-cfg=cfg(elm_kernel_profile,values(\"035f323b73bf4db169bc1d69e615f0a5f7c35393a5d2d0055895c289e27ae384\"))",
]

[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
rustflags = [
    "-C",
    "link-arg=-Telm.ld",
    "-C",
    "relocation-model=pic",
    "-C",
    "code-model=small",
    "-C",
    "link-arg=-pie",
    "-C",
    "link-arg=-z",
    "-C",
    "link-arg=notext",
    "-C",
    "link-arg=--gc-sections",
    "-C",
    "link-arg=--build-id=none",
    "--cfg=elm_kernel_api=\"contest-2026\"",
    "--check-cfg=cfg(elm_kernel_api,values(\"contest-2026\"))",
    "--cfg=elm_kernel_profile=\"035f323b73bf4db169bc1d69e615f0a5f7c35393a5d2d0055895c289e27ae384\"",
    "--check-cfg=cfg(elm_kernel_profile,values(\"035f323b73bf4db169bc1d69e615f0a5f7c35393a5d2d0055895c289e27ae384\"))",
]

[target.loongarch64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-C",
    "link-arg=-Telm.ld",
    "-C",
    "relocation-model=pic",
    "-C",
    "code-model=small",
    "-C",
    "link-arg=-pie",
    "-C",
    "link-arg=-z",
    "-C",
    "link-arg=notext",
    "-C",
    "link-arg=--gc-sections",
    "-C",
    "link-arg=--build-id=none",
    "-A",
    "named_asm_labels",
    "--cfg=elm_kernel_api=\"contest-2026\"",
    "--check-cfg=cfg(elm_kernel_api,values(\"contest-2026\"))",
    "--cfg=elm_kernel_profile=\"035f323b73bf4db169bc1d69e615f0a5f7c35393a5d2d0055895c289e27ae384\"",
    "--check-cfg=cfg(elm_kernel_profile,values(\"035f323b73bf4db169bc1d69e615f0a5f7c35393a5d2d0055895c289e27ae384\"))",
]
