// efi_guids.c - 标准 EFI GUID 常量定义

#include "efi_types.h"

const EfiStatus EFI_STATUS_SUCCESS = EFI_SUCCESS_VALUE;
const EfiStatus EFI_STATUS_LOAD_ERROR = EFI_LOAD_ERROR_VALUE;
const EfiStatus EFI_STATUS_INVALID_PARAMETER = EFI_INVALID_PARAMETER_VALUE;
const EfiStatus EFI_STATUS_UNSUPPORTED = EFI_UNSUPPORTED_VALUE;
const EfiStatus EFI_STATUS_BAD_BUFFER_SIZE = EFI_BAD_BUFFER_SIZE_VALUE;
const EfiStatus EFI_STATUS_BUFFER_TOO_SMALL = EFI_BUFFER_TOO_SMALL_VALUE;
const EfiStatus EFI_STATUS_NOT_READY = EFI_NOT_READY_VALUE;
const EfiStatus EFI_STATUS_DEVICE_ERROR = EFI_DEVICE_ERROR_VALUE;
const EfiStatus EFI_STATUS_WRITE_PROTECTED = EFI_WRITE_PROTECTED_VALUE;
const EfiStatus EFI_STATUS_OUT_OF_RESOURCES = EFI_OUT_OF_RESOURCES_VALUE;
const EfiStatus EFI_STATUS_VOLUME_CORRUPTED = EFI_VOLUME_CORRUPTED_VALUE;
const EfiStatus EFI_STATUS_VOLUME_FULL = EFI_VOLUME_FULL_VALUE;
const EfiStatus EFI_STATUS_NO_MEDIA = EFI_NO_MEDIA_VALUE;
const EfiStatus EFI_STATUS_MEDIA_CHANGED = EFI_MEDIA_CHANGED_VALUE;
const EfiStatus EFI_STATUS_NOT_FOUND = EFI_NOT_FOUND_VALUE;
const EfiStatus EFI_STATUS_ACCESS_DENIED = EFI_ACCESS_DENIED_VALUE;
const EfiStatus EFI_STATUS_NO_RESPONSE = EFI_NO_RESPONSE_VALUE;
const EfiStatus EFI_STATUS_NO_MAPPING = EFI_NO_MAPPING_VALUE;
const EfiStatus EFI_STATUS_TIMEOUT = EFI_TIMEOUT_VALUE;
const EfiStatus EFI_STATUS_NOT_STARTED = EFI_NOT_STARTED_VALUE;
const EfiStatus EFI_STATUS_ALREADY_STARTED = EFI_ALREADY_STARTED_VALUE;
const EfiStatus EFI_STATUS_ABORTED = EFI_ABORTED_VALUE;
const EfiStatus EFI_STATUS_ICMP_ERROR = EFI_ICMP_ERROR_VALUE;
const EfiStatus EFI_STATUS_TFTP_ERROR = EFI_TFTP_ERROR_VALUE;
const EfiStatus EFI_STATUS_PROTOCOL_ERROR = EFI_PROTOCOL_ERROR_VALUE;
const EfiStatus EFI_STATUS_INCOMPATIBLE_VERSION = EFI_INCOMPATIBLE_VERSION_VALUE;
const EfiStatus EFI_STATUS_SECURITY_VIOLATION = EFI_SECURITY_VIOLATION_VALUE;
const EfiStatus EFI_STATUS_CRC_ERROR = EFI_CRC_ERROR_VALUE;
const EfiStatus EFI_STATUS_END_OF_MEDIA = EFI_END_OF_MEDIA_VALUE;
const EfiStatus EFI_STATUS_END_OF_FILE = EFI_END_OF_FILE_VALUE;
const EfiStatus EFI_STATUS_INVALID_LANGUAGE = EFI_INVALID_LANGUAGE_VALUE;
const EfiStatus EFI_STATUS_COMPROMISED_DATA = EFI_COMPROMISED_DATA_VALUE;
const EfiStatus EFI_STATUS_IP_ADDRESS_CONFLICT = EFI_IP_ADDRESS_CONFLICT_VALUE;
const EfiStatus EFI_STATUS_HTTP_ERROR = EFI_HTTP_ERROR_VALUE;
const EfiStatus EFI_STATUS_WARN_UNKNOWN_GLYPH = EFI_WARN_UNKNOWN_GLYPH_VALUE;
const EfiStatus EFI_STATUS_WARN_DELETE_FAILURE = EFI_WARN_DELETE_FAILURE_VALUE;
const EfiStatus EFI_STATUS_WARN_WRITE_FAILURE = EFI_WARN_WRITE_FAILURE_VALUE;
const EfiStatus EFI_STATUS_WARN_BUFFER_TOO_SMALL = EFI_WARN_BUFFER_TOO_SMALL_VALUE;
const EfiStatus EFI_STATUS_WARN_STALE_DATA = EFI_WARN_STALE_DATA_VALUE;
const EfiStatus EFI_STATUS_WARN_FILE_SYSTEM = EFI_WARN_FILE_SYSTEM_VALUE;
const EfiStatus EFI_STATUS_WARN_RESET_REQUIRED = EFI_WARN_RESET_REQUIRED_VALUE;

const uint32_t EFI_MEMORY_TYPE_RESERVED_MEMORY_TYPE = EFI_RESERVED_MEMORY_TYPE;
const uint32_t EFI_MEMORY_TYPE_LOADER_CODE = EFI_LOADER_CODE;
const uint32_t EFI_MEMORY_TYPE_LOADER_DATA = EFI_LOADER_DATA;
const uint32_t EFI_MEMORY_TYPE_BOOT_SERVICES_CODE = EFI_BOOT_SERVICES_CODE;
const uint32_t EFI_MEMORY_TYPE_BOOT_SERVICES_DATA = EFI_BOOT_SERVICES_DATA;
const uint32_t EFI_MEMORY_TYPE_RUNTIME_SERVICES_CODE = EFI_RUNTIME_SERVICES_CODE;
const uint32_t EFI_MEMORY_TYPE_RUNTIME_SERVICES_DATA = EFI_RUNTIME_SERVICES_DATA;
const uint32_t EFI_MEMORY_TYPE_CONVENTIONAL_MEMORY = EFI_CONVENTIONAL_MEMORY;
const uint32_t EFI_MEMORY_TYPE_UNUSABLE_MEMORY = EFI_UNUSABLE_MEMORY;
const uint32_t EFI_MEMORY_TYPE_ACPI_RECLAIM_MEMORY = EFI_ACPI_RECLAIM_MEMORY;
const uint32_t EFI_MEMORY_TYPE_ACPI_MEMORY_NVS = EFI_ACPI_MEMORY_NVS;
const uint32_t EFI_MEMORY_TYPE_MEMORY_MAPPED_IO = EFI_MEMORY_MAPPED_IO;
const uint32_t EFI_MEMORY_TYPE_MEMORY_MAPPED_IO_PORT_SPACE = EFI_MEMORY_MAPPED_IO_PORT_SPACE;
const uint32_t EFI_MEMORY_TYPE_PAL_CODE = EFI_PAL_CODE;
const uint32_t EFI_MEMORY_TYPE_PERSISTENT_MEMORY = EFI_PERSISTENT_MEMORY;
const uint32_t EFI_MEMORY_TYPE_MAX_MEMORY_TYPE = EFI_MAX_MEMORY_TYPE;

/// ACPI 2.0 RSDP GUID
/// {8868E871-E4F1-11D3-BC22-0080C73C8881}
const EfiGuid ACPI_20_TABLE_GUID = {
    .data1 = 0x8868E871,
    .data2 = 0xE4F1,
    .data3 = 0x11D3,
    .data4 = {0xBC, 0x22, 0x00, 0x80, 0xC7, 0x3C, 0x88, 0x81},
};

/// FDT (Device Tree) GUID
/// {B1B621D5-F19C-41A5-830B-D9152C69AAE0}
const EfiGuid FDT_TABLE_GUID = {
    .data1 = 0xB1B621D5,
    .data2 = 0xF19C,
    .data3 = 0x41A5,
    .data4 = {0x83, 0x0B, 0xD9, 0x15, 0x2C, 0x69, 0xAA, 0xE0},
};

/// SMBIOS 3.x GUID
/// {F2FD1544-9794-4A2C-992E-E5BBCF20E394}
const EfiGuid SMBIOS3_TABLE_GUID = {
    .data1 = 0xF2FD1544,
    .data2 = 0x9794,
    .data3 = 0x4A2C,
    .data4 = {0x99, 0x2E, 0xE5, 0xBB, 0xCF, 0x20, 0xE3, 0x94},
};

/// ACPI 1.0 RSDP GUID
/// {EB9D2D30-2D88-11D3-9A16-0090273FC14D}
const EfiGuid ACPI_TABLE_GUID = {
    .data1 = 0xEB9D2D30,
    .data2 = 0x2D88,
    .data3 = 0x11D3,
    .data4 = {0x9A, 0x16, 0x00, 0x90, 0x27, 0x3F, 0xC1, 0x4D},
};

/// EFI Loaded Image Protocol GUID
/// {5B1B31A1-9562-11D2-8E3F-00A0C969723B}
const EfiGuid LOADED_IMAGE_PROTOCOL_GUID = {
    .data1 = 0x5B1B31A1,
    .data2 = 0x9562,
    .data3 = 0x11d2,
    .data4 = {0x8E, 0x3F, 0x00, 0xA0, 0xC9, 0x69, 0x72, 0x3B},
};

/// EFI Simple Pointer Protocol GUID
/// {31878C87-0B75-11D5-9A4F-0090273FC14D}
const EfiGuid SIMPLE_POINTER_PROTOCOL_GUID = {
    .data1 = 0x31878C87,
    .data2 = 0x0B75,
    .data3 = 0x11d5,
    .data4 = {0x9A, 0x4F, 0x00, 0x90, 0x27, 0x3F, 0xC1, 0x4D},
};

/// EFI Simple Text Input Protocol GUID
/// {387477C1-69C7-11D2-8E39-00A0C969723B}
const EfiGuid SIMPLE_TEXT_INPUT_PROTOCOL_GUID = {
    .data1 = 0x387477C1,
    .data2 = 0x69C7,
    .data3 = 0x11D2,
    .data4 = {0x8E, 0x39, 0x00, 0xA0, 0xC9, 0x69, 0x72, 0x3B},
};

/// EFI Simple Text Output Protocol GUID
/// {387477C2-69C7-11D2-8E39-00A0C969723B}
const EfiGuid SIMPLE_TEXT_OUTPUT_PROTOCOL_GUID = {
    .data1 = 0x387477C2,
    .data2 = 0x69C7,
    .data3 = 0x11D2,
    .data4 = {0x8E, 0x39, 0x00, 0xA0, 0xC9, 0x69, 0x72, 0x3B},
};
